id: P39CB2DBA
initial_creation_type: ocr
source_metadata:
  volumes:
    2475e7bfe92844c88060e17b8d6157b7:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: གོས་སྔོན་པོ་ཅན་གྱི་དངོས་གྲུབ་ཉེ་བ།
      total_pages: 1379
      volume_number: 37
